extends Node2D
class_name LolottesThroneRoom

@onready var ego: Node2D = $"../ego"

func _ready() -> void:
    pass

func _on_room_looked() -> void:
    pass

func _on_kq4_091_castle_dining_room_interacted() -> void:
    var target_scene = load("res://scenes/kq4_091_castle_dining_room/kq4_091_castle_dining_room.tscn")
    if target_scene:
        get_tree().change_scene_to_packed(target_scene)

func _on_kq4_093_bottom_of_east_tower_interacted() -> void:
    var target_scene = load("res://scenes/kq4_093_bottom_of_east_tower/kq4_093_bottom_of_east_tower.tscn")
    if target_scene:
        get_tree().change_scene_to_packed(target_scene)

func _on_kq4_080_lolottes_castle_entrance_interacted() -> void:
    var target_scene = load("res://scenes/kq4_080_lolottes_castle_entrance/kq4_080_lolottes_castle_entrance.tscn")
    if target_scene:
        get_tree().change_scene_to_packed(target_scene)
