extends Scene 	

func _on_room_looked() -> void:
	pass

func _on_kq4_017_spooky_house_exterior_interacted() -> void:
	var target_scene = load("res://scenes/kq4_017_spooky_house_exterior/kq4_017_spooky_house_exterior.tscn")
	if target_scene:
		get_tree().change_scene_to_packed(target_scene)

func _on_kq4_067_the_parlor_interacted() -> void:
	var target_scene = load("res://scenes/kq4_067_the_parlor/kq4_067_the_parlor.tscn")
	if target_scene:
		get_tree().change_scene_to_packed(target_scene)

func _on_kq4_060_bedroom_interacted() -> void:
	var target_scene = load("res://scenes/kq4_060_bedroom/kq4_060_bedroom.tscn")
	if target_scene:
		get_tree().change_scene_to_packed(target_scene)

func _on_kq4_062_bedroom_interacted() -> void:
	var target_scene = load("res://scenes/kq4_062_bedroom/kq4_062_bedroom.tscn")
	if target_scene:
		get_tree().change_scene_to_packed(target_scene)

func _on_kq4_064_old_dining_room_interacted() -> void:
	var target_scene = load("res://scenes/kq4_064_old_dining_room/kq4_064_old_dining_room.tscn")
	if target_scene:
		get_tree().change_scene_to_packed(target_scene)

func _on_foyer_exit_interacted() -> void:
	$foyer_exit.default_script(self)
