extends Node2D
class_name StoneTowerStairs

@onready var ego: Node2D = $"../ego"

func _ready() -> void:
    pass

func _on_room_looked() -> void:
    pass

func _on_kq4_093_bottom_of_east_tower_interacted() -> void:
    var target_scene = load("res://scenes/kq4_093_bottom_of_east_tower/kq4_093_bottom_of_east_tower.tscn")
    if target_scene:
        get_tree().change_scene_to_packed(target_scene)

func _on_kq4_082_lolottes_tower_bedroom_interacted() -> void:
    var target_scene = load("res://scenes/kq4_082_lolottes_tower_bedroom/kq4_082_lolottes_tower_bedroom.tscn")
    if target_scene:
        get_tree().change_scene_to_packed(target_scene)

func _on_kq4_087_east_end_of_hallway_interacted() -> void:
    var target_scene = load("res://scenes/kq4_087_east_end_of_hallway/kq4_087_east_end_of_hallway.tscn")
    if target_scene:
        get_tree().change_scene_to_packed(target_scene)
