extends Scene

func _on_room_looked() -> void:
    pass

func _on_kq4_072_dark_cave_passage_interacted() -> void:
    var target_scene = load("res://scenes/kq4_072_dark_cave_passage/kq4_072_dark_cave_passage.tscn")
    if target_scene:
        get_tree().change_scene_to_packed(target_scene)

func _on_kq4_074_troll_cave_interacted() -> void:
    var target_scene = load("res://scenes/kq4_074_troll_cave/kq4_074_troll_cave.tscn")
    if target_scene:
        get_tree().change_scene_to_packed(target_scene)

func _on_kq4_070_waterfall_cave_interacted() -> void:
    var target_scene = load("res://scenes/kq4_070_waterfall_cave/kq4_070_waterfall_cave.tscn")
    if target_scene:
        get_tree().change_scene_to_packed(target_scene)
