extends Node2D
class_name EastEndOfHallway

@onready var ego: Node2D = $"../ego"

func _ready() -> void:
    pass

func _on_room_looked() -> void:
    pass

func _on_kq4_086_dim_hallway_west_end_interacted() -> void:
    var target_scene = load("res://scenes/kq4_086_dim_hallway_west_end/kq4_086_dim_hallway_west_end.tscn")
    if target_scene:
        get_tree().change_scene_to_packed(target_scene)

func _on_kq4_084_cottage_front_interacted() -> void:
    var target_scene = load("res://scenes/kq4_084_cottage_front/kq4_084_cottage_front.tscn")
    if target_scene:
        get_tree().change_scene_to_packed(target_scene)

func _on_kq4_088_stone_tower_stairs_interacted() -> void:
    var target_scene = load("res://scenes/kq4_088_stone_tower_stairs/kq4_088_stone_tower_stairs.tscn")
    if target_scene:
        get_tree().change_scene_to_packed(target_scene)
