extends Node2D
class_name CastleDiningRoom

@onready var ego: Node2D = $"../ego"

func _ready() -> void:
    pass

func _on_room_looked() -> void:
    pass

func _on_kq4_090_west_tower_bottom_interacted() -> void:
    var target_scene = load("res://scenes/kq4_090_west_tower_bottom/kq4_090_west_tower_bottom.tscn")
    if target_scene:
        get_tree().change_scene_to_packed(target_scene)

func _on_kq4_092_lolottes_throne_room_interacted() -> void:
    var target_scene = load("res://scenes/kq4_092_lolottes_throne_room/kq4_092_lolottes_throne_room.tscn")
    if target_scene:
        get_tree().change_scene_to_packed(target_scene)

func _on_kq4_089_castle_kitchen_interacted() -> void:
    var target_scene = load("res://scenes/kq4_089_castle_kitchen/kq4_089_castle_kitchen.tscn")
    if target_scene:
        get_tree().change_scene_to_packed(target_scene)
